/* Automatically generated by './build/bin/build-entry.js' */

import Singler from '../packages/singler/index'

const components = [
    Singler,
];

const install = function(Vue) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};


if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
    install,
    Singler
};



// import Table from './table.vue';
/* istanbul ignore next */
// Table.install = function(Vue) {
//   Vue.component(Table.name, Table);
// };
// export default Table;
// Vue.component('my-component-name', {
// // ... 选项 ...
// })
// 这些组件是全局注册的。也就是说它们在注册之后可以用在任何新创建的 Vue 根实例 (new Vue) 的模板中。